boundaries fixups: ordering of parts, do not add newline on boundary if there's no part after previous header (#34)
* Fix IMAP mailbox maintanence

Update message's mailbox id in a separate explicit transaction to prevent
SQLException: ORA-01453 error on the next db_begin_transaction() call
(see db_mailbox_seq_update() next to 'UPDATE dbmail_messages SET mailbox_idnr'
query).

* add newline only if is_message

* better fix for rfc822 multipart messages with boundary after header

* fixed some race condition when closing boundaries, since key does not change.  Needed ordering parts on depth DESC when key does not vary.

* fixes ordering in insertion